---
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-api-config
  namespace: eshop
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"
  ConnectionStrings__catalogdb: "Host=postgres;Database=catalog;Username=eshop;Password=eshop123"
  EventBus__ConnectionString: "amqp://eshop:eshop123@rabbitmq:5672"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
  namespace: eshop
  labels:
    app: catalog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
      - name: catalog-api
        image: catalog-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: catalog-api-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: catalog-api
  namespace: eshop
  labels:
    app: catalog-api
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: catalog-api
